"""initial schema

Revision ID: 020634c8f304
Revises: 
Create Date: 2026-09-04 01:58:22.813656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020634c8f304'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_image', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_programme_id'), 'maps', ['programme_id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_programme_id'), 'phases', ['programme_id'], unique=False)
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('target_xp', sa.Integer(), nullable=False),
    sa.Column('weekly_target_xp', sa.Integer(), nullable=True),
    sa.Column('max_group_penalty_percent', sa.Float(), nullable=False),
    sa.Column('active_theme_id', sa.Integer(), nullable=True),
    sa.Column('active_map_id', sa.Integer(), nullable=True),
    sa.Column('active_phase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['active_phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['active_theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_active'), 'programmes', ['active'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('primary', sa.String(length=20), nullable=False),
    sa.Column('secondary', sa.String(length=20), nullable=False),
    sa.Column('accent', sa.String(length=20), nullable=False),
    sa.Column('background', sa.String(length=20), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_programme_id'), 'themes', ['programme_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('xp_bonus', sa.Integer(), nullable=False),
    sa.Column('group_xp_bonus', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'code', name='uq_programme_badge_code')
    )
    op.create_index(op.f('ix_badges_programme_id'), 'badges', ['programme_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('game_type', sa.String(length=100), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('participation_xp', sa.Integer(), nullable=False),
    sa.Column('elite_xp', sa.Integer(), nullable=False),
    sa.Column('winner_xp', sa.Integer(), nullable=False),
    sa.Column('group_xp', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_phase_id'), 'challenges', ['phase_id'], unique=False)
    op.create_index(op.f('ix_challenges_programme_id'), 'challenges', ['programme_id'], unique=False)
    op.create_table('conduct_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('xp_penalty', sa.Integer(), nullable=False),
    sa.Column('restorative_required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('tier >= 1 AND tier <= 3', name='ck_conduct_rule_tier'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conduct_rules_programme_id'), 'conduct_rules', ['programme_id'], unique=False)
    op.create_table('flash_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notification_title', sa.String(length=200), nullable=True),
    sa.Column('notification_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_events_programme_id'), 'flash_events', ['programme_id'], unique=False)
    op.create_index(op.f('ix_flash_events_scheduled_at'), 'flash_events', ['scheduled_at'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_programme_id'), 'groups', ['programme_id'], unique=False)
    op.create_table('map_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('x >= 0 AND x <= 1', name='ck_map_location_x'),
    sa.CheckConstraint('y >= 0 AND y <= 1', name='ck_map_location_y'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_locations_map_id'), 'map_locations', ['map_id'], unique=False)
    op.create_table('point_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('individual_xp', sa.Integer(), nullable=False),
    sa.Column('group_xp', sa.Integer(), nullable=False),
    sa.Column('weekly_cap', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'code', name='uq_programme_point_rule_code')
    )
    op.create_index(op.f('ix_point_rules_programme_id'), 'point_rules', ['programme_id'], unique=False)
    op.create_table('programme_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_definitions.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'game_id', name='uq_programme_game')
    )
    op.create_index(op.f('ix_programme_games_game_id'), 'programme_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_programme_games_programme_id'), 'programme_games', ['programme_id'], unique=False)
    op.create_table('programme_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('xp_threshold', sa.Integer(), nullable=False),
    sa.Column('reward_description', sa.String(length=500), nullable=True),
    sa.Column('reward_value', sa.Float(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_milestones_programme_id'), 'programme_milestones', ['programme_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_phase_id'), 'resources', ['phase_id'], unique=False)
    op.create_index(op.f('ix_resources_programme_id'), 'resources', ['programme_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('editable_by_staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'key', name='uq_programme_setting_key')
    )
    op.create_index(op.f('ix_system_settings_programme_id'), 'system_settings', ['programme_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_code'), 'attendance_sessions', ['code'], unique=True)
    op.create_index(op.f('ix_attendance_sessions_group_id'), 'attendance_sessions', ['group_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_programme_id'), 'attendance_sessions', ['programme_id'], unique=False)
    op.create_table('group_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('collective_complicity', sa.Boolean(), nullable=False),
    sa.Column('severe_shared_impact', sa.Boolean(), nullable=False),
    sa.Column('passive_group_endorsement', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('restorative_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_group_penalty_positive_amount'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_penalties_programme_id'), 'group_penalties', ['programme_id'], unique=False)
    op.create_table('phase_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['map_locations.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'location_id', name='uq_phase_location')
    )
    op.create_index(op.f('ix_phase_locations_location_id'), 'phase_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_phase_locations_phase_id'), 'phase_locations', ['phase_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('gamertag', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_visible', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_active'), 'players', ['active'], unique=False)
    op.create_index(op.f('ix_players_gamertag'), 'players', ['gamertag'], unique=True)
    op.create_index('ix_players_group_active', 'players', ['group_id', 'active'], unique=False)
    op.create_index(op.f('ix_players_group_id'), 'players', ['group_id'], unique=False)
    op.create_index('ix_players_public_visibility', 'players', ['public_visible', 'active'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=True)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('xp_threshold', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('mystery', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_programme_id'), 'rewards', ['programme_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'player_id', name='uq_attendance_session_player')
    )
    op.create_index(op.f('ix_attendance_player_id'), 'attendance', ['player_id'], unique=False)
    op.create_index(op.f('ix_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_table('challenge_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('performance_percentile', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('participation_awarded', sa.Boolean(), nullable=False),
    sa.Column('elite_awarded', sa.Boolean(), nullable=False),
    sa.Column('winner_awarded', sa.Boolean(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_attempts_challenge_id'), 'challenge_attempts', ['challenge_id'], unique=False)
    op.create_index('ix_challenge_attempts_challenge_score', 'challenge_attempts', ['challenge_id', 'score'], unique=False)
    op.create_index(op.f('ix_challenge_attempts_player_id'), 'challenge_attempts', ['player_id'], unique=False)
    op.create_table('community_award_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_award_tokens_group_id'), 'community_award_tokens', ['group_id'], unique=False)
    op.create_index(op.f('ix_community_award_tokens_player_id'), 'community_award_tokens', ['player_id'], unique=False)
    op.create_index(op.f('ix_community_award_tokens_programme_id'), 'community_award_tokens', ['programme_id'], unique=False)
    op.create_index(op.f('ix_community_award_tokens_token_hash'), 'community_award_tokens', ['token_hash'], unique=True)
    op.create_table('community_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=200), nullable=True),
    sa.Column('submitted_by_organisation', sa.String(length=200), nullable=True),
    sa.Column('submitted_by_contact', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_awards_group_id'), 'community_awards', ['group_id'], unique=False)
    op.create_index(op.f('ix_community_awards_player_id'), 'community_awards', ['player_id'], unique=False)
    op.create_index(op.f('ix_community_awards_programme_id'), 'community_awards', ['programme_id'], unique=False)
    op.create_index(op.f('ix_community_awards_status'), 'community_awards', ['status'], unique=False)
    op.create_index('ix_community_awards_status_created', 'community_awards', ['status', 'created_at'], unique=False)
    op.create_table('conduct_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('conduct_rule_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('restorative_completed', sa.Boolean(), nullable=False),
    sa.Column('points_reinstated', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conduct_rule_id'], ['conduct_rules.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conduct_incidents_player_id'), 'conduct_incidents', ['player_id'], unique=False)
    op.create_index(op.f('ix_conduct_incidents_programme_id'), 'conduct_incidents', ['programme_id'], unique=False)
    op.create_table('engagement_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_flags_player_id'), 'engagement_flags', ['player_id'], unique=False)
    op.create_index('ix_engagement_flags_player_status', 'engagement_flags', ['player_id', 'status'], unique=False)
    op.create_index(op.f('ix_engagement_flags_programme_id'), 'engagement_flags', ['programme_id'], unique=False)
    op.create_table('kudos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('giver_player_id', sa.Integer(), nullable=False),
    sa.Column('recipient_player_id', sa.Integer(), nullable=False),
    sa.Column('reaction_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('giver_player_id != recipient_player_id', name='ck_kudos_not_self'),
    sa.ForeignKeyConstraint(['giver_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['recipient_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kudos_giver_player_id'), 'kudos', ['giver_player_id'], unique=False)
    op.create_index(op.f('ix_kudos_programme_id'), 'kudos', ['programme_id'], unique=False)
    op.create_index('ix_kudos_recipient_created', 'kudos', ['recipient_player_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kudos_recipient_player_id'), 'kudos', ['recipient_player_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_player_id'), 'notifications', ['player_id'], unique=False)
    op.create_index(op.f('ix_notifications_programme_id'), 'notifications', ['programme_id'], unique=False)
    op.create_table('player_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'badge_id', name='uq_player_badge')
    )
    op.create_index(op.f('ix_player_badges_badge_id'), 'player_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_player_badges_player_id'), 'player_badges', ['player_id'], unique=False)
    op.create_table('player_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_rewards_player_id'), 'player_rewards', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_rewards_reward_id'), 'player_rewards', ['reward_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'endpoint', name='uq_push_player_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_player_id'), 'push_subscriptions', ['player_id'], unique=False)
    op.create_table('skill_trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('tree_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_trees_player_id'), 'skill_trees', ['player_id'], unique=False)
    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('group_amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount != 0 OR group_amount != 0', name='ck_xp_transaction_non_zero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_created_at'), 'xp_transactions', ['created_at'], unique=False)
    op.create_index('ix_xp_transactions_group_created', 'xp_transactions', ['group_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_group_id'), 'xp_transactions', ['group_id'], unique=False)
    op.create_index('ix_xp_transactions_player_created', 'xp_transactions', ['player_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_player_id'), 'xp_transactions', ['player_id'], unique=False)
    op.create_index('ix_xp_transactions_programme_created', 'xp_transactions', ['programme_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_programme_id'), 'xp_transactions', ['programme_id'], unique=False)
    op.create_index(op.f('ix_xp_transactions_transaction_type'), 'xp_transactions', ['transaction_type'], unique=False)
    op.create_table('manual_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('xp_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['xp_transaction_id'], ['xp_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_awards_group_id'), 'manual_awards', ['group_id'], unique=False)
    op.create_index(op.f('ix_manual_awards_player_id'), 'manual_awards', ['player_id'], unique=False)
    op.create_index(op.f('ix_manual_awards_programme_id'), 'manual_awards', ['programme_id'], unique=False)
    op.create_table('skill_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_tree_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('reward_description', sa.String(length=500), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_tree_id'], ['skill_trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_milestones_skill_tree_id'), 'skill_milestones', ['skill_tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_milestones_skill_tree_id'), table_name='skill_milestones')
    op.drop_table('skill_milestones')
    op.drop_index(op.f('ix_manual_awards_programme_id'), table_name='manual_awards')
    op.drop_index(op.f('ix_manual_awards_player_id'), table_name='manual_awards')
    op.drop_index(op.f('ix_manual_awards_group_id'), table_name='manual_awards')
    op.drop_table('manual_awards')
    op.drop_index(op.f('ix_xp_transactions_transaction_type'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_programme_id'), table_name='xp_transactions')
    op.drop_index('ix_xp_transactions_programme_created', table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_player_id'), table_name='xp_transactions')
    op.drop_index('ix_xp_transactions_player_created', table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_group_id'), table_name='xp_transactions')
    op.drop_index('ix_xp_transactions_group_created', table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_created_at'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index(op.f('ix_skill_trees_player_id'), table_name='skill_trees')
    op.drop_table('skill_trees')
    op.drop_index(op.f('ix_push_subscriptions_player_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_player_rewards_reward_id'), table_name='player_rewards')
    op.drop_index(op.f('ix_player_rewards_player_id'), table_name='player_rewards')
    op.drop_table('player_rewards')
    op.drop_index(op.f('ix_player_badges_player_id'), table_name='player_badges')
    op.drop_index(op.f('ix_player_badges_badge_id'), table_name='player_badges')
    op.drop_table('player_badges')
    op.drop_index(op.f('ix_notifications_programme_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_player_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_kudos_recipient_player_id'), table_name='kudos')
    op.drop_index('ix_kudos_recipient_created', table_name='kudos')
    op.drop_index(op.f('ix_kudos_programme_id'), table_name='kudos')
    op.drop_index(op.f('ix_kudos_giver_player_id'), table_name='kudos')
    op.drop_table('kudos')
    op.drop_index(op.f('ix_engagement_flags_programme_id'), table_name='engagement_flags')
    op.drop_index('ix_engagement_flags_player_status', table_name='engagement_flags')
    op.drop_index(op.f('ix_engagement_flags_player_id'), table_name='engagement_flags')
    op.drop_table('engagement_flags')
    op.drop_index(op.f('ix_conduct_incidents_programme_id'), table_name='conduct_incidents')
    op.drop_index(op.f('ix_conduct_incidents_player_id'), table_name='conduct_incidents')
    op.drop_table('conduct_incidents')
    op.drop_index('ix_community_awards_status_created', table_name='community_awards')
    op.drop_index(op.f('ix_community_awards_status'), table_name='community_awards')
    op.drop_index(op.f('ix_community_awards_programme_id'), table_name='community_awards')
    op.drop_index(op.f('ix_community_awards_player_id'), table_name='community_awards')
    op.drop_index(op.f('ix_community_awards_group_id'), table_name='community_awards')
    op.drop_table('community_awards')
    op.drop_index(op.f('ix_community_award_tokens_token_hash'), table_name='community_award_tokens')
    op.drop_index(op.f('ix_community_award_tokens_programme_id'), table_name='community_award_tokens')
    op.drop_index(op.f('ix_community_award_tokens_player_id'), table_name='community_award_tokens')
    op.drop_index(op.f('ix_community_award_tokens_group_id'), table_name='community_award_tokens')
    op.drop_table('community_award_tokens')
    op.drop_index(op.f('ix_challenge_attempts_player_id'), table_name='challenge_attempts')
    op.drop_index('ix_challenge_attempts_challenge_score', table_name='challenge_attempts')
    op.drop_index(op.f('ix_challenge_attempts_challenge_id'), table_name='challenge_attempts')
    op.drop_table('challenge_attempts')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_player_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_rewards_programme_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index('ix_players_public_visibility', table_name='players')
    op.drop_index(op.f('ix_players_group_id'), table_name='players')
    op.drop_index('ix_players_group_active', table_name='players')
    op.drop_index(op.f('ix_players_gamertag'), table_name='players')
    op.drop_index(op.f('ix_players_active'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_phase_locations_phase_id'), table_name='phase_locations')
    op.drop_index(op.f('ix_phase_locations_location_id'), table_name='phase_locations')
    op.drop_table('phase_locations')
    op.drop_index(op.f('ix_group_penalties_programme_id'), table_name='group_penalties')
    op.drop_table('group_penalties')
    op.drop_index(op.f('ix_attendance_sessions_programme_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_group_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_code'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_system_settings_programme_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_resources_programme_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_phase_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_programme_milestones_programme_id'), table_name='programme_milestones')
    op.drop_table('programme_milestones')
    op.drop_index(op.f('ix_programme_games_programme_id'), table_name='programme_games')
    op.drop_index(op.f('ix_programme_games_game_id'), table_name='programme_games')
    op.drop_table('programme_games')
    op.drop_index(op.f('ix_point_rules_programme_id'), table_name='point_rules')
    op.drop_table('point_rules')
    op.drop_index(op.f('ix_map_locations_map_id'), table_name='map_locations')
    op.drop_table('map_locations')
    op.drop_index(op.f('ix_groups_programme_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_flash_events_scheduled_at'), table_name='flash_events')
    op.drop_index(op.f('ix_flash_events_programme_id'), table_name='flash_events')
    op.drop_table('flash_events')
    op.drop_index(op.f('ix_conduct_rules_programme_id'), table_name='conduct_rules')
    op.drop_table('conduct_rules')
    op.drop_index(op.f('ix_challenges_programme_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_phase_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_badges_programme_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_programme_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_programmes_active'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_phases_programme_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_maps_programme_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_table('game_definitions')
    # ### end Alembic commands ###
