"""add XP balance projection tables

Revision ID: 0c50ed9e34bb
Revises: 202609061955
Create Date: 2026-09-06 21:15:12.431653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0c50ed9e34bb'
down_revision: Union[str, Sequence[str], None] = '202609061955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_xp_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('lifetime_xp_awarded', sa.Integer(), nullable=False),
    sa.Column('lifetime_xp_removed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_xp_balances_programme_id'), 'group_xp_balances', ['programme_id'], unique=True)
    op.create_table('player_xp_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('lifetime_xp', sa.Integer(), nullable=False),
    sa.Column('lifetime_xp_removed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_xp_balances_player_id'), 'player_xp_balances', ['player_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_point_rule_weekly_cap_positive', 'point_rules', type_='check')
    op.drop_constraint('ck_point_rule_individual_xp_non_negative', 'point_rules', type_='check')
    op.drop_constraint('ck_point_rule_individual_award_cap_positive', 'point_rules', type_='check')
    op.drop_constraint('ck_point_rule_has_positive_reward', 'point_rules', type_='check')
    op.drop_constraint('ck_point_rule_group_xp_non_negative', 'point_rules', type_='check')
    op.drop_constraint('ck_point_rule_group_award_cap_positive', 'point_rules', type_='check')
    op.drop_constraint('ck_point_rule_awards_per_week_non_negative', 'point_rules', type_='check')
    op.drop_constraint('uq_programme_point_rule_code', 'point_rules', type_='unique')
    op.drop_index(op.f('ix_player_xp_balances_player_id'), table_name='player_xp_balances')
    op.drop_table('player_xp_balances')
    op.drop_index(op.f('ix_group_xp_balances_programme_id'), table_name='group_xp_balances')
    op.drop_table('group_xp_balances')
    # ### end Alembic commands ###
