"""Add reference fields to Notification model for XP transaction linking

Revision ID: c21776d78fd6
Revises: 0c50ed9e34bb
Create Date: 2026-09-14 22:58:03.567965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c21776d78fd6'
down_revision: Union[str, Sequence[str], None] = '0c50ed9e34bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('reference_type', sa.String(length=100), nullable=True))
        # batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))
        batch_op.create_index('uq_notification_reference', ['reference_type', 'reference_id'], unique=True)

    # op.alter_column('programme_economies', 'id',
#                existing_type=sa.INTEGER(),
#                nullable=False,
#                autoincrement=True)
    # op.alter_column('programme_economies', 'max_staff_multiplier',
#                existing_type=sa.REAL(),
#                type_=sa.Float(),
#                existing_nullable=False,
#                existing_server_default=sa.text('(1.3)'))
    # op.alter_column('programme_economies', 'weekly_growth_cap_multiplier',
#                existing_type=sa.REAL(),
#                type_=sa.Float(),
#                existing_nullable=False,
#                existing_server_default=sa.text('(1.1)'))
    # op.create_index(op.f('ix_programme_economies_programme_id'), 'programme_economies', ['programme_id'], unique=True)
    # op.create_foreign_key(None, 'programme_economies', 'programmes', ['programme_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'programme_economies', type_='foreignkey')
    # op.drop_index(op.f('ix_programme_economies_programme_id'), table_name='programme_economies')
    # op.alter_column('programme_economies', 'weekly_growth_cap_multiplier',
#                existing_type=sa.Float(),
#                type_=sa.REAL(),
#                existing_nullable=False,
#                existing_server_default=sa.text('(1.1)'))
    # op.alter_column('programme_economies', 'max_staff_multiplier',
#                existing_type=sa.Float(),
#                type_=sa.REAL(),
#                existing_nullable=False,
#                existing_server_default=sa.text('(1.3)'))
    # op.alter_column('programme_economies', 'id',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                autoincrement=True)
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('uq_notification_reference')
        # batch_op.drop_column('reference_id')
        # batch_op.drop_column('reference_type')
    # ### end Alembic commands ###